language: python

cache:
    apt
    pip
python:
  - 2.7
env:
before_install:
  - sudo apt-get --assume-yes install python-setuptools python-dev build-essential python-pip python-pycurl librtmp-dev git libxml2-dev libxslt1-dev
  - sudo apt-get --assume-yes install libzmq-dev python-zmq
  - sudo apt-get --assume-yes install libcurl4-openssl-dev libcurl4-gnutls-dev
  - sudo apt-get --assume-yes install tshark 

  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  - sudo echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org

  - wget https://raw.githubusercontent.com/renatosamperio/context_task_queue/master/requirements.txt
  - pip install -r requirements.txt

  - wget https://github.com/KimiNewt/pyshark/archive/master.zip
  - unzip master.zip; cd pyshark-master/
  - wget https://raw.githubusercontent.com/renatosamperio/context_task_queue/master/Tools/Install/fix_export_xml.patch
  - patch src/pyshark/packet/layer.py < fix_export_xml.patch
  - cd src && sudo python setup.py install && cd ../..
  - rm -rf pyshark-master; rm master.zip

  - wget https://github.com/renatosamperio/context_task_queue/archive/master.zip
  - unzip master.zip && cd context_task_queue-master

install:
  - sudo python setup.py install install_scripts

script: travis_retry python setup.py test
