language: python

cache:
    apt
    pip
python:
  - 2.7

before_install:
  - |
    sudo apt-get update
    sudo apt-get --assume-yes install libzmq-dev
    sudo apt-get --assume-yes install python-dev build-essential librtmp-dev git libxml2-dev libxslt1-dev
    sudo apt-get --assume-yes install libcurl4-openssl-dev 
    sudo apt-get --assume-yes install libcurl4-gnutls-dev
    sudo apt-get --assume-yes install tshark 

  - |
    sudo pip install --upgrade pip
    sudo pip install --upgrade google-api-python-client
    sudo pip install --upgrade psutil
    sudo pip install --upgrade xmltodict
    sudo pip install --upgrade oauth2client
    sudo pip install --upgrade pymongo
    sudo pip install --upgrade dicttoxml
    sudo pip install --upgrade paramiko

  - |
    wget https://github.com/KimiNewt/pyshark/archive/master.zip
    unzip master.zip; cd pyshark-master/
    wget https://raw.githubusercontent.com/renatosamperio/context_task_queue/master/Tools/Install/fix_export_xml.patch
    patch src/pyshark/packet/layer.py < fix_export_xml.patch
    cd src && sudo python setup.py install && cd ../..
    sudo rm -rf pyshark-master; rm master.zip
    
  - |
    ls -la /usr/local/lib/python2.7/dist-packages/
    export PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages/pyshark-0.3.6.2-py2.7.egg"
    export PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages/Logbook-1.0.0-py2.7-linux-x86_64.egg"
    export PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages/trollius-1.0.4-py2.7.egg"
    export PYTHONPATH="${PYTHONPATH}:/usr/local/lib/python2.7/dist-packages/lxml-3.7.2-py2.7-linux-x86_64.egg"
    python -c "import pyshark"
    
install:
  - |
    sudo python setup.py install install_scripts
    ls -la /usr/local/lib/python2.7/dist-packages/
    python -c "import Services"

script: travis_retry pytest
